GET http://localhost:5065/games

###
GET http://localhost:5065/games/fe9963b5-a79c-4f4b-a6d7-131aeb778a8f

###
POST http://localhost:5065/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genreId": "b8a77400-e414-4e5a-a695-c3ec90ce6177",
    "price": 19.99,
    "releaseDate": "2011-11-18",
    "description": "A sandbox game that allows players to build and explore virtual worlds made of blocks."
}

###
PUT http://localhost:5065/games/ff9f5f37-b80e-49ce-b484-f5154dcaabc4
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genre": "Fighting",
    "price": 9.99,
    "releaseDate": "1992-07-15"
}

###
DELETE http://localhost:5065/games/583a7003-1113-4877-8a68-24f15ea233df

###
GET http://localhost:5065/genres