GET http://localhost:5065/games

###
GET http://localhost:5065/games/ef74c558-94c6-4346-8fb9-15410cb8c96d

###
POST http://localhost:5065/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5065/games/ff9f5f37-b80e-49ce-b484-f5154dcaabc4
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genre": "Fighting",
    "price": 9.99,
    "releaseDate": "1992-07-15"
}